Resources: 
  # The EC2 instqnce running the wordpress site. 
  EC2:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-97785bed"
      IntanceType: "t.micro"
      Tags:
        - "myFirstCFInstance"
        - "wordpress"

  # Static pages for the wordpress site.
  S3:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: "wp-xxxxxx" # To be replaced by unique name.
  
  # MySQL database instance for wordpress site.
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: 5
      StorageType: "gp2"
      DBInstanceClass: "db.t2.micro"
      Engine: "mysql"
      MasterUsername: "WordpressUser"
      MasterUserPassword: "W0rdPr355"
      Tags:
        - "myRDSInstance"
        - "wordpress"
