Parameters: 
  EnvironmentSize:
    Type: String
    Default: SMALL
    AllowedValues:
      - SMALL
      - MEDIUM
      - LARGE
    Description: Select environment size (S,M,L)

Mappings:
  RegionMap:
    us-east-1:
      "AMI": "ami-97785bed" 
    us-east-2:
      "AMI": "ami-f63b1193"
    eu-west-1:
      "AMI": "ami-d834aba1"
    eu-west-2:
      "AMI": "ami-403e2524"
  InstanceSize:
    SMALL:
      "EC2": "t2.micro"
      "DB": "db.t2.micro"
    MEDIUM:
      "EC2": "t2.small"
      "DB": "db.t2.small"
    LARGE:
      "EC2": "t2.medium"
      "DB": "db.t2.medium"


Resources: 
  # The EC2 instance running the wordpress site. 
  EC2:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMI] # Find correct Linux AMI to use based on current Region.
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      Tags:
        - 
          Key: "Name"
          Value:  "wordpress_inc"

  # Storage for static pages for the wordpress site.
  S3:
    Type: "AWS::S3::Bucket"
    Properties: 
      Tags: 
        - 
          Key: "Name"
          Value:  "wordpress_inc"
  
  # MySQL database instance for wordpress site data.
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: 5
      StorageType: "gp2"
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB]
      Engine: "mysql"
      MasterUsername: "WordpressUser"
      MasterUserPassword: "W0rdPr355"
      Tags:
        - 
          Key: "Name"
          Value:  "wordpress_inc"
