Resources: 
  # The EC2 instance running the wordpress site. 
  EC2:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-1853ac65" # us-east 1 amazon linux AMI
      InstanceType: "t2.micro"
      Tags:
        - 
          Key: "Name"
          Value:  "wordpress_inc"

  # Storage for static pages for the wordpress site.
  S3:
    Type: "AWS::S3::Bucket"
    Properties: 
      BucketName: "wp-jaws9s8d74jfdx1" # To be replaced by unique name.
      Tags: 
        - 
          Key: "Name"
          Value:  "wordpress_inc"
  
  # MySQL database instance for wordpress site data.
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties: 
      AllocatedStorage: 5
      StorageType: "gp2"
      DBInstanceClass: "db.t2.micro"
      Engine: "mysql"
      MasterUsername: "WordpressUser"
      MasterUserPassword: "W0rdPr355"
      Tags:
        - 
          Key: "Name"
          Value:  "wordpress_inc"
